name: cpp-ops

on:
  workflow_call:

jobs:
  test:
    runs-on: cpp
    steps:
      - uses: actions/checkout@v6
      - shell: bash
        run: |
          SKBUILD_CMAKE_ARGS="-DFLAGGEMS_BUILD_C_EXTENSIONS=ON" pip install --no-build-isolation -v -e .
      - shell: bash
        run: |
          cd build/cpython-311/ctests
          export FLAGGEMS_SOURCE_DIR=$(python -c "import os;import flag_gems;print(os.path.dirname(flag_gems.__file__))")
          ctest -V
