name: mkdocs

on:
  workflow_call:

  schedule:
    - cron: '0 16 * * *'

jobs:
  build-doc:
    runs-on: docs
    steps:
      - uses: actions/checkout@v6
      - shell: bash
        run: |
          mkdocs build
          echo "Website: http://120.92.44.177/gems_docs/"
      - if: github.event_name == 'schedule'
        shell: bash
        run: |
          mkdocs build --config-file mkdocs.yml --site-dir /html/gems_docs
