name: triage
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - id: labeler
        uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
      - id: sizer
        uses: codelytv/pr-size-labeler@v1
        with:
          xs_label: 'size/XSmall'
          xs_max_size: '10'
          s_label: 'size/Small'
          s_max_size: '100'
          m_label: 'size/Medium'
          m_max_size: '500'
          l_label: 'size/Large'
          l_max_size: '1000'
          xl_label: 'size/XLarge'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          github_api_url: 'https://api.github.com'
          files_to_ignore: ''
